### ISSUE TITLE
Post URL

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/wordpress-plugin#11]
Send the post's URL to Frost (along with content, etc).

> This issue is blocked until `url` param is supported by the Frost API

**Comment by geoffturk** [comment]
Needs poetapp/frost-api#27

**Comment by lautarodragan** [comment]
@krobi64 we have a new attribute that could be used for this in verifiable claims right?

**Comment by geoffturk** [comment]
@markparolisi The idea here is to make the WP blog URL part of the work claim file data. This might be a one-liner, or not. :-)

**Comment by markparolisi** [comment]
Not sure if we want to use the pretty URL or the GUID. Technically, we should use the GUID because it's immutable, but if services use that URL publicly to route traffic, then everybody is going to be hitting 301's from the GUID to the pretty URL. 
Either way, yeah it's likely a one liner.

**Comment by geoffturk** [comment]
@lautarodragan What do you suggest? Put the GUID in the canonicalUrl?

**Comment by geoffturk** [comment]
@markparolisi Just discussed this with Lautaro. We should use the pretty URL as the value for the key of `canonicalUrl`. Thanks.
