### ISSUE TITLE
ReadMe: requires at least

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/wordpress-plugin#12]
Make sure the `Requires at least` entry in the readme is correct. It should have the lowest WordPress version possible with which the plugin works correctly.

**Comment by haydenyoung** [comment]
Tested 3.3 (didn't install)

Tested 4.0 

Po.et plugin failed with errror:

PHP Fatal error:  Uncaught Error: Call to undefined function wp_json_encode()

Tested 4.1, installed and functioned correctly.
