### ISSUE TITLE
Error on publish

### ISSUE THREAD

**Issue by lketchersid** [poetapp/wordpress-plugin#24]
I have the plug-in installed and put the badge tag in a post. When I published, the post does indeed publish, and the badge is there, but Wordpress spit back out the following error.

Fatal error: Call to undefined function wp_json_encode() in /homepages/45/d88109300/htdocs/dusk/wordpress/wp-content/plugins/po-et/includes/class-poet-consumer.php on line 74

Running version 1.0.1 of the plug-in, and an old version of Wordpress (3.9) which may be the issue.

**Comment by lautarodragan** [comment]
Hey @lketchersid! I believe the plugin requires at least WP version 4.1 to run correctly.

Can you try with a newer version?

**Comment by lketchersid** [comment]
Updated to 4.9.5, made a single character change and then republished. Didn't see there error and now see the content when I hit the frost API. Thanks for the assistance!
