### ISSUE TITLE
Consistent Code Style

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/wordpress-plugin#3]
The code style has some inconsistencies. This is a minor issue and doesn't affect end users.

**Comment by haydenyoung** [comment]
While I recommend the PHP PSR coding standard (http://www.php-fig.org/psr/psr-2/), WP has not yet implemented this so I suggest we stick to the WP style; https://codex.wordpress.org/WordPress_Coding_Standards.

**Comment by markparolisi** [comment]
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
