### ISSUE TITLE
Error on Activation

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/wordpress-plugin#32]
This error was reported by a user.

> I have the latest version of Wordpress installed and the Po.et plug-in is also updated.  Nevertheless, when I attempt to activate it, I am getting this error:

```
Can't use function return value in write context in .../plugins/po-et/poet.php on line 246
```

I haven't been able to reproduce it with version 1.0.2 and WP version Version 4.9.6.

**Comment by geoffturk** [comment]
I've reached out to the person who reported the error to get more details about his setup.

**Comment by geoffturk** [comment]
Closing because I never received a reply from this person.
