### ISSUE TITLE
Badge in Non-Timestamped Articles

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/wordpress-plugin#4]
The Po.et Badge should either not be rendered at all or be rendered in its "Timestamping Pending" version when a WordPress Post doesn't have an associated Frost Work ID in its meta.

https://github.com/poetapp/wordpress-plugin/blob/8e101c93296966af2ad56a31e0bf03771f662776/PoetArticlePoster/PoetArticlePoster.php#L336-L345

**Comment by haydenyoung** [comment]
Addressed in pull request #29.
