### ISSUE TITLE
Update default API URL

### ISSUE THREAD

**Issue by geoffturk** [poetapp/wordpress-plugin#43]
Change the API URL from "https://api.frost.po.et/works" to "https://api.poetnetwork.net/works"

**Comment by geoffturk** [comment]
@markparolisi This one is necessary to work with the new version of the API we are just launching this week.

**Comment by markparolisi** [comment]
OK, I'll update these and also make them filterable so one could set code like...

```
if($is_dev_env){
  add_filter('poet_api_url', function(){
    return $sandbox_api_url;
  })
}

```

Same concept with the filters for explorer endpoint

**Comment by lautarodragan** [comment]
Extracted part of this into https://github.com/poetapp/wordpress-plugin/issues/45
