### ISSUE TITLE
Timestamp on beta2 plugin is off by 6 hours

### ISSUE THREAD

**Issue by lketchersid** [poetapp/wordpress-plugin#55]
Installed the beta2 plug-in. Currently have WP 4.9.8.
The poe.et badge at the bottom of this article (https://www.duskbeforethedawn.net/2018/12/po-et-on-mainnet-testing-po-et-beta-plug-in/) says December 8, 03:51. It was updated December 7 at 21:51. I'm not sure where it is pulling the time from. Is this GMT?

Let me know if you need more information.

**Comment by geoffturk** [comment]
Yes, the badge date/time is always displayed using GMT/UTC.
