### ISSUE TITLE
No settings in plug-in page, but settings in settings area

### ISSUE THREAD

**Issue by lketchersid** [poetapp/wordpress-plugin#56]
Not sure if this is intended but with the current production testnet plugin, there is a link to settings on the plug-in page. The beta2 did not have this - but there was a settings for po.et in the settings area.

WP 4.9.8

Please let me know if you need more information.

**Comment by lautarodragan** [comment]
Thank you @lketchersid! The intention is to get that link to the settings page back into the plugin page.

**Comment by geoffturk** [comment]
See #31

**Comment by lautarodragan** [comment]
Closing as dup of https://github.com/poetapp/wordpress-plugin/issues/31
