### ISSUE TITLE
Update URLs to new prod

### ISSUE THREAD

**Issue by WesleyCharlesBlake** [poetapp/wordpress-plugin#58]
We need to update the URLs for the API and the front end to show the new production URLs:

API: https://api.poetnetwork.net/works
App: https://explorer.poetnetwork.net

**Comment by lautarodragan** [comment]
This is already so in `master`.

https://github.com/poetapp/wordpress-plugin/blob/5c3ffa50d0bffd455e1882ddbf423182c79d7cea/includes/class-poet-activator.php#L24-L35

The ability to switch between testnet and mainnet links is tracked in https://github.com/poetapp/wordpress-plugin/issues/45.

We do need to update links in the README.md and readme.txt. Working on it: https://github.com/poetapp/wordpress-plugin/pull/59/files
