### ISSUE TITLE
Poet shortcode in template

### ISSUE THREAD

**Issue by tnwhitwell** [poetapp/wordpress-plugin#9]
I’ve created a child theme which automatically adds the po.et badge under each of my posts, using do_shortcode().

This works a treat for individual pages, but when added to the view_all template, the badge only renders for the first instance.

Unsure if this is a wordpress limitation, or an oddity of the plugin. My Google fu is failing me on this. Assistance appreciated.

**Comment by lautarodragan** [comment]
Hey @tnwhitwell, we had a look at this but we aren't sure what's going on either.  

Is there any chance you could provide the source code of the child theme you're working on?

**Comment by tnwhitwell** [comment]
For sure:
```php
<?php
/**
 * Template part for displaying posts.
 *
 * @package Simppeli
 */

?>

<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<header class="entry-header">

		<?php
			if ( is_single() ) :
				the_title( '<h1 class="entry-title">', '</h1>' );
			else :
				the_title( sprintf( '<h2 class="entry-title"><a href="%s" rel="bookmark">', esc_url( get_permalink() ) ), '</a></h2>' );
			endif;
		?>

		<?php if ( 'post' == get_post_type() ) : ?>
		<div class="entry-meta">
			<?php simppeli_posted_on(); ?>
		</div><!-- .entry-meta -->
		<?php endif; ?>

		<?php simppeli_post_thumbnail(); ?>

	</header><!-- .entry-header -->

	<div class="entry-content">
		<?php
			/* translators: %s: Name of current post */
			the_content( sprintf(
				wp_kses( __( 'Continue reading %s <span class="meta-nav">&rarr;</span>', 'simppeli' ), array( 'span' => array( 'class' => array() ) ) ),
				the_title( '<span class="screen-reader-text">"', '"</span>', false )
			) );
		?>

		<?php
			wp_link_pages( array(
				'before'      => '<div class="page-links"><span class="page-links-title">' . esc_html__( 'Pages:', 'simppeli' ) . '</span>',
				'after'       => '</div>',
				'link_before' => '<span>',
				'link_after'  => '</span>',
				'pagelink'    => '<span class="screen-reader-text">' . esc_html__( 'Page', 'simppeli' ) . ' </span>%',
				'separator'   => '<span class="screen-reader-text">, </span>',
			) );
		?>
	</div><!-- .entry-content -->

	<footer class="entry-footer">
		<?php simppeli_entry_footer(); ?>
                <?php echo do_shortcode("[poet-badge]"); ?>
	</footer><!-- .entry-footer -->
</article><!-- #post-## -->
```
```php
		<?php if ( have_posts() ) : ?>

			<?php /* Start the Loop */ ?>
			<?php while ( have_posts() ) : the_post(); ?>

				<?php

					/*
					 * Include the Post-Format-specific template for the content.
					 * If you want to override this in a child theme, then include a file
					 * called content-___.php (where ___ is the Post Format name) and that will be used instead.
					 */
					get_template_part( 'template-parts/content', get_post_format() );
				?>

			<?php endwhile; ?>

			<?php the_posts_navigation(); ?>

		<?php else : ?>

			<?php get_template_part( 'template-parts/content', 'none' ); ?>

		<?php endif; ?>
```

Examples:
* [Single post (working)](https://tom.whitwell.xyz/2017/07/encrypted-automatic-off-site-backup-replication-with-rclone/)
* [listing of all (badge only showing for first)](https://tom.whitwell.xyz/)

**Comment by haydenyoung** [comment]
@tnwhitwell, okay strange that it doesn't show for anything but the first post. I'm wondering if either subsequent posts are using a different template (unlikely) or whether only the first blog post details are being passed to the short code. We'll try your scripts and see what is going on with the shortcode.

We're also considering the option of removing the Po.et shortcode altogether and injecting the poet badge directly into the bottom of the_content. Of course there are questions raised about the rigidity of the layout if we do this but in most cases it would simplify the requirements around including the poet badge.
